### ISSUE TITLE
realsense sdk "make -j1" error

### ISSUE THREAD

**Issue by waversrijan** [acrobotic/Ai_Demos_RPi#8]
I'm on a RPI 4 with raspbian running on it. When I run the "make -j1" for the installation of realsense sdk. The process reaches 55% and then throws error.

[ 55%] Linking CXX executable rs-hello-realsense
/usr/bin/ld: ../../librealsense2.so.2.50.0: undefined reference to `__atomic_load_8'
/usr/bin/ld: ../../librealsense2.so.2.50.0: undefined reference to `__atomic_store_8'
/usr/bin/ld: ../../librealsense2.so.2.50.0: undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/hello-realsense/CMakeFiles/rs-hello-realsense.dir/build.make:110: examples/hello-realsense/rs-hello-realsense] Error 1
make[1]: *** [CMakeFiles/Makefile2:1240: examples/hello-realsense/CMakeFiles/rs-hello-realsense.dir/all] Error 2
make: *** [Makefile:149: all] Error 2`

**Comment by JIeSchnee** [comment]
Blocked by the same issue~ Did you find the solution?

**Comment by waversrijan** [comment]
No progress

**Comment by waversrijan** [comment]
> Blocked by the same issue~ Did you find the solution?

No progress

**Comment by Coderooni** [comment]
> I'm on a RPI 4 with raspbian running on it. When I run the "make -j1" for the installation of realsense sdk. The process reaches 55% and then throws error.
> 
> [ 55%] Linking CXX executable rs-hello-realsense /usr/bin/ld: ../../librealsense2.so.2.50.0: undefined reference to `__atomic_load_8' /usr/bin/ld: ../../librealsense2.so.2.50.0: undefined reference to `__atomic_store_8' /usr/bin/ld: ../../librealsense2.so.2.50.0: undefined reference to `__atomic_fetch_add_8' collect2: error: ld returned 1 exit status make[2]: *** [examples/hello-realsense/CMakeFiles/rs-hello-realsense.dir/build.make:110: examples/hello-realsense/rs-hello-realsense] Error 1 make[1]: *** [CMakeFiles/Makefile2:1240: examples/hello-realsense/CMakeFiles/rs-hello-realsense.dir/all] Error 2 make: *** [Makefile:149: all] Error 2`

Are you running the 32-bit version of Raspbian OS? I ran into the same exact issue and tried out multiple different methods before wiping out the SD card and installing a fresh copy of the 64-bit OS. After that, I followed the 1st step in this comment
https://github.com/IntelRealSense/librealsense/issues/6964#issuecomment-707501049

Once that was done, I followed acrobatic's tutorial in its entirety, and I've managed to successfully run realsense-viewer and the librealsense python wrapper.

**Comment by waversrijan** [comment]
I fixed it another way. https://github.com/IntelRealSense/librealsense/issues/9962#issuecomment-996104753
